# Generated by Django 2.0.1 on 2018-01-27 10:56

from django.db import migrations, models
import django.db.models.deletion
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.Sensor')),
                ('state_on', models.BooleanField()),
            ],
            bases=('sensors.sensor',),
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('sensor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.Sensor')),
                ('state_free', models.BooleanField()),
            ],
            bases=('sensors.sensor',),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('pollution', 'pollution'), ('electricity', 'electricity'), ('street_light', 'street_light'), ('parking_lot', 'parking_lot')], default='pollution', max_length=50),
            preserve_default=False,
        ),
    ]
